#!/bin/bash
# $Id: slacfile,v 1.10 2009/02/16 10:23:58 mibl Exp mibl $
# $Revision: 1.10 $
#
# Shell Script to run at 23:59.
# E-mails the apache logfile to slac
# (c) Mike Blomgren 2003

MAILER=/usr/bin/nail
APACHECONF=/etc/httpd/conf/httpd.conf
SECSRCH="/usr/local/slac/secsrch.pl"
OUTDIR="/var/www/htdocs/slac/"

#Set date format to whatever your apache logger uses
DATE=`date  +"%Y-%m-%d"`

# Set from address to where the results should be sent returned to
FROM=miblo@yahoo.com

#LOGDIR="/usr/local/apache2/logs /var/wwwtornado/logs"
LOGDIR="/var/wwwtornado/logs"

# The SLAC receiving address
TO=logger@a52.mine.nu

SLEEPTIME=90
#LF=`cat $APACHECONF | grep LogFormat | grep -v \# `
#ls -la $LOGFILE

if [ "X$1" != "X" ]; 
    then SLEEPTIME=0;
    DATE=$1;
    #echo $SLEEPTIME;
    #echo $DATE;

fi


sleep $SLEEPTIME

for DIR in $LOGDIR  ; do
  echo "Directory: $DIR" 

  LOGFILE=$DIR/access-$DATE.log

  # Mailling Logfile to Slac Service
  CMD="$MAILER -a $LOGFILE -r $FROM -s '$DATE' $TO"
  echo "Executing: $CMD"
  logger -p local2.info -i "$CMD"
  echo . | $CMD

  # Copying 
  #CMD="$SECSRCH $LOGFILE $OUTDIR"
  #echo "Executing $SECSRCH as: $CMD"
  #logger -p local2.info -i "Executing $CMD"
  #$CMD

done

# And that's all folks.
